# Maple Dark 

foreground            #cbd5e1
background            #1e1e1f
selection_background  #475569
selection_foreground  #cbd5e1

cursor                #8d9db4

# black / gray
color0  #333333
color8  #666666

# red
color1  #edabab
color9  #ffc4c4

# green
color2  #a4dfae
color10 #bdf8c7

# yellow
color3  #eecfa0
color11 #ffe8b9

# blue
color4  #8fc7ff
color12 #a8e0ff

# magenta
color5  #d2ccff
color13 #ebe5ff

# cyan
color6  #a1e8e5
color14 #bafffe

# white
color7  #f3f2f2
color15 #ffffff

# tabs / UI
active_tab_background   #232a39
active_tab_foreground   #cbd5e1
inactive_tab_background #171718
inactive_tab_foreground #999999

url_color #8dbe74
