backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.15;
shadow-offset-x = -8;
shadow-offset-y = -8;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 8;
